name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea.

  - type: dropdown
    id: package
    attributes:
      label: Target Package
      description: Which package should this feature be added to?
      options:
        - ssi-credentials
        - ssi-crypto
        - ssi-did
        - ssi-did-key
        - ssi-did-web
        - ssi-issuer-sdk
        - ssi-verifier-sdk
        - ssi-wallet-sdk
        - ssi-revocation
        - ssi-schema
        - ssi-storage
        - ssi-types
        - ssi-utils
        - New package
        - Multiple packages
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What you'd like to happen
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Other solutions you've considered
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature request